spring.application.name=crypto-backend

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/crypto_db
spring.datasource.username=postgres
spring.datasource.password=S3rg1024!

# Configuración de Hibernate (Crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Puerto del servidor backend
server.port=8082